name: lucknow_explore
description: Offline multilingual tourist guide app for Lucknow
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_tts: ^3.8.3
  google_mlkit_translation: ^0.8.0
  google_mlkit_commons: ^0.5.0
  path_provider: ^2.1.2
  just_audio: ^0.9.34
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/audio/
    - assets/data/descriptions.json
    - assets/images/logo.png
    - assets/lang/en_description.json
    - assets/images/rumi/gallery/
    - assets/images/the_residency/gallery/

